language: rust
sudo: false

jobs:
  include:
  - stage: test
    script:
    - cargo test -p tokio-trace
    - cargo test -p tokio-trace-futures
    - cargo test -p tokio-trace-subscriber
    - cargo test -p tokio-trace-tower
    - cargo test -p tokio-trace-tower-http
    - cargo test -p tokio-trace-log
    - cargo test -p tokio-trace-env-logger
    name: "tests"
    rust:
    # This represents the minimum Rust version supported by Tokio. Updating this
    # should be done in a dedicated PR and cannot be greater than two 0.x
    # releases prior to the current stable.
    - 1.26.0
    - stable
    - beta
    - nightly
  # The proc macros crate does _not_ build on Rust 1.26.0, so it is tested
  # in a separate stage.
  - stage: test
    script:
    - cargo test -p tokio-trace-macros
    name: "test proc-macros"
    rust:
    - stable
    - beta
    - nightly
  - script: cargo fmt --all -- --check
    install: rustup component add rustfmt-preview
    name: "rustfmt"
