language: rust
sudo: false

jobs:
  include:
  - stage: test
    script: cargo test --all -- --test-threads 1
    name: "tests"
  - script: cargo fmt --all -- --check
    install: rustup component add rustfmt-preview
    name: "rustfmt"
