[package]
name = "tokio-trace"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[dependencies]
futures = "0.1"
log = "0.4"
lazy_static = "1"

[dev-dependencies]
env_logger = "0.5"
ansi_term = "0.11"
humantime = "1.1.1"
