[package]
name = "example"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]

[dependencies]
tokio-trace = { path = "../../tokio-trace" }
tokio-trace-macros = { path = "../tokio-trace-macros" }
ansi_term = "0.11"
humantime = "1.1.1"
